### ISSUE TITLE
Questions around multiple speakers and radarr/sonarr in Docker

### ISSUE THREAD

**Issue by spicerackk** [avraham/hass_radarr_sonarr_search_by_voice#17]
As heading suggests, I am curious on how to implement this so I can ask any speaker in my house for requests. 

Also struggling to wrap my head around how I would add root paths for Radarr and Sonarr when they are in a Docker container on my Windows machine, whilst Hassio is running on an R-Pi. Any help would be appreciated!

**Comment by avraham** [comment]
Hi,

The way I implemented is using IFTTT to process the request and it sends to
Home Assistant the title in a variable so the script can do the rest.

You can ask to any of your speakers, the issue would be that Home Assistant
needs to know to which speaker should it send the script response. (Whether
it successfully added the request or not).
As far as I know with this method you can't know from which speaker the
request was initiated.

About the root path on a different host, it shouldn't matter if radarr and
sonarr are on a different host. You can define the IP address of each host
in the config file.
Since you are using docker, the root path is the virtual path your radarr
app has access to. It the same path it shows on the UI when you add a movie
manually.

**Comment by spicerackk** [comment]
Thanks for the response, I was able to get the test line working, however same as the other issue mentioned about saying it can't add the movie yet. I will work on the rest throughout today and see how I go with it :)
